language: java

addons:
  sonarcloud:
    organization: "jayhem10"
      # token:
    # secure: "**************************" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonarclean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=011086a17c58bbbf6546d68e14ff073f038ee242